---
title: Key Terms in Official Statistics
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
    theme: cerulean
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This page holds a list of key official statistics terms and their definitions.

# Diffusion indices (動向指數)

## What Is a Diffusion Index?
A diffusion index is a statistic derived from survey responses. Consider a survey panel where participants answer multiple choice questions about an economic series of interest. For example, in the Richmond Fed monthly business surveys, manufacturing- and service-sector firms are asked to respond to the statement "Compared to the previous month, the number of employees at your firm has..." with "decreased," "stayed the same" or "increased."

In this case, the diffusion index is the share of respondents who said that an indicator improved (here, employment increased) minus the share of respondents who said that an indicator deteriorated (here, employment decreased).

For example, out of 132 respondents, 63 reported that employment increased, 25 reported that it decreased, and 44 reported that it stayed the same. Thus, the diffusion index would be 0.29 (63/132 – 25/132). The Richmond Fed then multiplies the reading by 100 and reports the employment diffusion index as 29. A value above 0 is interpreted as an expansion in employment, and a value below 0 is interpreted as a contraction.

## How Should a Diffusion Index Be Used?
A diffusion index provides information on the extensive margin of change (the number of firms that reported a change) but not on the intensive margin of change (the amount of that change). In comparison, employment data from the Bureau of Labor Statistics (BLS) reflects changes in both the intensive and extensive margins. For example, a 200,000-job gain reported by the BLS is a net change in employment, reflecting the net employment change at each individual firm (the intensive margin) across all firms (the extensive margin).

## Why Use a Diffusion Index?
Diffusion indexes are a useful way to summarize economic information from surveys because they are easy to understand and correlate well with economic activity over time. To use diffusion indexes most effectively as a measure of change, however, it is important that the extensive margin of the indicator in question explains more of the change in that indicator than the intensive margin. 

## Hong Kong examples
Business sentiment statistics in Hong Kong, e.g. Quarterly Business Tendency Survey, Monthly Survey on the Business Situation of SMEs.

## References
Website: [Federal Reserve Bank of Richmond](https://www.richmondfed.org/publications/research/economic_brief/2022/eb_22-22)

Journal article:

*   [The Information Content and Statistical Properties of Diffusion Indexes](References/DiffusionIndices/ijcb20q3a2.pdf)
*   [Macroeconomic Forecasting Using Diffusion Indexes](References/DiffusionIndices/macroeconomic_forecasting_using_diffusion_indexes.pdf)





# Prices

## Consumer Prices

### Headline consumer price inflation (整體消費物價通脹率)


### Underlying consumer price inflation (基本消費物價通脹率)
Underlying consumer price inflation is calculated by netting out the effects of all the Government’s one-off relief measures introduced since 2007, including the waiver and the Government’s payment of public housing rentals, rates concessions, the suspension and subsequent abolition of the Employees Retraining Levy, subsidies for household electricity charges, and waivers of examination fees.

計算基本消費物價通脹率時， 已撇除所有自二零零七年起實施的政府一次性紓緩措施所造成的效應； 這些措施包括公屋租金寬免和政府代繳公屋租金、差餉寬減、暫停和後來取消收取僱員再培訓徵款、住戶電費補貼， 以及考試費寬免。

(Sources: C&SD publications)

### CPI and cost of living index

The CPI is sometimes loosely taken as a **cost-of-living index**. Strictly speaking, there is a distinction between these two types of indices. While the CPI relates to the price changes of a fixed basket of consumer goods and services, a cost of living index measures the change in the cost of maintaining a given standard of living, or level of utility. It is very difficult to produce a valid cost-of-living index which would need to take account of, among other things, changes in standard of living and the substitutions that consumers make in their purchases in endeavouring to maintain their standard of living.


# External trade

## Terms of trade
Terms of trade are defined as the ratio between the index of export prices and the index of import prices. If the export prices increase more than the import prices, a country has a positive terms of trade, as for the same amount of exports, it can purchase more imports. (Source: )
